-- World Cup predictor MVP setup
-- Run this in Supabase SQL editor.

create table if not exists wc_matches (
  id bigint generated by default as identity primary key,
  home_team text not null,
  away_team text not null,
  kickoff_at timestamptz not null,
  stage text,
  status text not null default 'upcoming' check (status in ('upcoming', 'played')),
  home_score int,
  away_score int,
  created_at timestamptz not null default now()
);

create table if not exists wc_predictions (
  id bigint generated by default as identity primary key,
  match_id bigint not null references wc_matches(id) on delete cascade,
  user_email text not null,
  user_name text not null,
  predicted_home int not null check (predicted_home >= 0),
  predicted_away int not null check (predicted_away >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, user_email)
);

create index if not exists idx_wc_matches_kickoff on wc_matches (kickoff_at);
create index if not exists idx_wc_predictions_email on wc_predictions (user_email);
create index if not exists idx_wc_predictions_match on wc_predictions (match_id);

create or replace function set_wc_predictions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_wc_predictions_updated_at on wc_predictions;
create trigger trg_wc_predictions_updated_at
before update on wc_predictions
for each row execute function set_wc_predictions_updated_at();

-- Optional: permissive RLS for MVP when no auth is used.
alter table wc_matches enable row level security;
alter table wc_predictions enable row level security;

drop policy if exists wc_matches_read_all on wc_matches;
create policy wc_matches_read_all on wc_matches
for select using (true);

drop policy if exists wc_predictions_read_all on wc_predictions;
create policy wc_predictions_read_all on wc_predictions
for select using (true);

drop policy if exists wc_predictions_write_all on wc_predictions;
create policy wc_predictions_write_all on wc_predictions
for all using (true) with check (true);

-- Example seed rows
-- insert into wc_matches(home_team, away_team, kickoff_at, stage, status)
-- values
-- ('France', 'Brazil', '2026-06-12T18:00:00Z', 'Journée 1', 'upcoming'),
-- ('Spain', 'Germany', '2026-06-13T20:00:00Z', 'Journée 1', 'upcoming');
